### ISSUE TITLE
get_publication gets lots of NAs

### ISSUE THREAD

**Issue by Maarten14C** [ropensci/neotoma#174]
Hi,
I am getting confused by the following:
allchrons <- get_dataset(,"geochronologic", gpid=2845) # could use wider search area but this one results a manageable 25 records instead of thousands
Then trying to find the corresponding publications (thanks to Simon for suggesting this):
pubs <- lapply(allchrons, function(x) get_publication(datasetid=x$dataset$dataset.id)) 
which results in mostly NAs. Only the last few fields result in publications. 

I think the confusion is with get_publication expecting publication IDs, not site IDs. How can I get the publication(s) for each site (or, even better, each chronological dataset ID)?

Gracias

Maarten

**Comment by SimonGoring** [comment]
Hi Maarten, I've tracked down the problem.  Unfortunately it seems to be a Neotoma issue that I will try to resolve on that end.

The issue is that Geochronological datasets were split off from other datasets recently (within the last year or so) and served up uniquely only recently.  As such many of them have unassigned publications.  In working with @andydawson we found several like this.

So, here's the second workaround for the problem as a gist.

https://gist.github.com/SimonGoring/2220586c4cedaf1f554c

I didn't try downloading everything, but it seems to work with most of the records.
