### ISSUE TITLE
`get_chroncontrol` returns error for chronology id 1430

### ISSUE THREAD

**Issue by andydawson** [ropensci/neotoma#178]
When I try to use get_chroncontrol to pull chronology with id 1430 I get the following:

`Error in do.call(rbind.data.frame, lapply(aa, "[[", "controls")[[1]]) : 
  second argument must be a list`

The core is varved, but does have a chronology id so I don't know if it actually exists in the neotoma db as a geochron object or not.

@SimonGoring :)

**Comment by SimonGoring** [comment]
It's a varved record that doesn't seem to have depth associated with the varves.  I'm going to check this a bit further but want to make some notes here:

* Currently (May 20, 2015) Neotoma has 8457 registered chronologies.  Of these, 2346 return errors.
* There is a big block of failing chronologies around 5500 - ~7500.
* Because of the neotoma structure we don't actually know what datasets these are associated with.
* In 2150 of the 2346 cases where `get_chroncontrol` fails, it fails because there is no information returned in the Neotoma API's  `data` slot, even though the object is returned with `success == 1`
* In the remaining 196 objects all have a length of 1, the `AgeType`s are distributed as one might expect (mostly Radiocarbon, a few Varves. . . )
* 194 of the records are the Default record.
* None of these records have Depth or Thickness fields.  This implies to me that these records are for single samples with depths defined somewhere else.
*  None of these records have a `controls` component.  They simply describe the model used, but don't define any age controls.

**Comment by SimonGoring** [comment]
The fix for this is now in a new branch [iss178](https://github.com/ropensci/neotoma/tree/iss178).  I'm going to leave it in the branch for a couple days.  I'm not sure if having returning an error or an empty chroncontrol is the best option.  If you want to check it out @andydawson let me know what you think.

**Comment by SimonGoring** [comment]
I've now merged the branch iss178 with the master branch as part of broader changes to `get_chroncontrol`.  This issue is resolved.
