### ISSUE TITLE
Failing travis build.

### ISSUE THREAD

**Issue by SimonGoring** [ropensci/neotoma#199]
We're getting a failure on travis build [99](https://travis-ci.org/ropensci/neotoma/builds/72189951), but the previous build worked fine.

I just ran the tests and checks on my computer and had no failures, there's no reason the test should be failing.  It's also not entirely clear to me which test it's actually failing.  I assume it's a test in ``test_simple_paper.R`, but they all passed fine for me as well.

Not sure what's up.  I made a super minor change with commit 475a43dfd0521abe2a0652be2fb342c9d3dfe8a6, basically to see if Travis would pass this time.  It didn't.

**Comment by SimonGoring** [comment]
I wonder if this is the same problem as we had with issue #160 where somehow we hit a limit on downloads and the build failed, even though for all intents and purposes there was no problem.  If that's the case, then we just have to remove some of the tests.

**Comment by gavinsimpson** [comment]
Is the limit imposed by the API? If the code is failing bc we don't have proper objects then we should be checking objects for completeness and issuing errors/warnings if found to be lacking.

If this is is the API rate-limiting or otherwise restricting the Travis machine from pulling in data, the we need to address that. I still think we should do this anyway, but we should cache objects to run the main tests (put them in `data/`) and then check that given the correct data the functions run. Then we should devise simpler/shorter tests for the package unit tests that actually test the API calling code works.

We're seeing too many of these failures and often it is hard to know what is wrong; if we don't know easily the users certainly don't. Therefore trying to capture some of these and thrown useful errors would be a good thing to implement to make the package more robust now that the code is post v1 release.

**Comment by SimonGoring** [comment]
I'll check with Mike & Brian at PSU.  That's a good point, I hadn't thought
of that.  I've never had a problem with rate-limiting on my computer and
I've loaded lots of data.  That said, I'll double check.

**Comment by SimonGoring** [comment]
Well, the build is passing again, with [102](https://travis-ci.org/ropensci/neotoma/builds/72510101).  I'm a bit at a loss here, but I'm closing this for now because I have too many outstanding issues.
