### ISSUE TITLE
neotoma dependency issues

### ISSUE THREAD

**Issue by IceAgeEcologist** [ropensci/neotoma#225]
@SimonGoring loading _neotoma_ in R leads to a series of dependency/installation issues... requires installing leaflet & shiny - shiny requires 'later', 'promises', 'rlang' which are available only in source form and may require compilation in C/C++/Fortran.    Can't load _neotoma_ without these dependencies resolved.

**Comment by SimonGoring** [comment]
Is this with:

‘install.packages()’ or with ’library(‘neotoma’)’?

Can you try a fresh install of the package and let me know the output of ‘sessionInfo()’?

**Comment by IceAgeEcologist** [comment]
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] lattice_0.20-33  permute_0.9-4    brglm_0.5-9      MASS_7.3-43     
 [5] grid_3.2.2       R6_2.2.2         jsonlite_1.4     nlme_3.1-121    
 [9] princurve_1.1-12 httr_1.3.1       vegan_2.4-3      Matrix_1.2-2    
[13] analogue_0.17-0  tools_3.2.2      yaml_2.1.14      parallel_3.2.2  
[17] cluster_2.0.3    mgcv_1.8-7

**Comment by IceAgeEcologist** [comment]
Also, the results of the install command (a fresh install; I removed neotoma prior to install):
> install.packages("neotoma")
Installing package into ‘C:/Users/Jack Williams/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
also installing the dependency ‘leaflet’


  There are binary versions available but the source versions are later:
        binary source needs_compilation
leaflet  1.0.1  2.0.1             FALSE
neotoma  1.6.2  1.7.0             FALSE

installing the source packages ‘leaflet’, ‘neotoma’

trying URL 'https://cran.rstudio.com/src/contrib/leaflet_2.0.1.tar.gz'
Content type 'application/x-gzip' length 2059787 bytes (2.0 MB)
downloaded 2.0 MB

trying URL 'https://cran.rstudio.com/src/contrib/neotoma_1.7.0.tar.gz'
Content type 'application/x-gzip' length 1310063 bytes (1.2 MB)
downloaded 1.2 MB

* installing *source* package 'leaflet' ...
** package 'leaflet' successfully unpacked and MD5 sums checked
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'shiny'
ERROR: lazy loading failed for package 'leaflet'
* removing 'C:/Users/Jack Williams/Documents/R/win-library/3.2/leaflet'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-32~1.2/bin/x64/R" CMD INSTALL -l "C:\Users\Jack Williams\Documents\R\win-library\3.2" C:\Users\JACKWI~1\AppData\Local\Temp\RtmpWwfX3I/downloaded_packages/leaflet_2.0.1.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘leaflet’ had non-zero exit status
ERROR: dependency 'leaflet' is not available for package 'neotoma'
* removing 'C:/Users/Jack Williams/Documents/R/win-library/3.2/neotoma'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-32~1.2/bin/x64/R" CMD INSTALL -l "C:\Users\Jack Williams\Documents\R\win-library\3.2" C:\Users\JACKWI~1\AppData\Local\Temp\RtmpWwfX3I/downloaded_packages/neotoma_1.7.0.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘neotoma’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\Jack Williams\AppData\Local\Temp\RtmpWwfX3I\downloaded_packages’

**Comment by gavinsimpson** [comment]
We had this issue today in you GAM workshop. The issue is that your R is too old for binaries for your OS to be available for some of the packages that *neotoma* directly or indirectly depends on. Further, you don't have RTools installed on your machine so you are unable to compile packages from source.

The easiest solution to this would be to update your R to the 3.5.x branch and then `install.packages()` will work. Alternatively, install Rtools (can be found on CRAN) so you can compile packages from sources, but this may unearth further dependencies on system libraries required by these other R packages.

We could look into the dependencies that *neotoma* actually has but this would be a longer-term effort; we might streamline *neotomoa* for example and try to minimise depedencies, perhaps moving non-core code that uses these extraneous dependencies to separate *neotoma-foo* add-on packages that allows a clean core with few dependencies but retain the functionality for those that want/need it.

**Comment by IceAgeEcologist** [comment]
Gavin, updated R to 3.5.x and that solved the problem.  Thanks!
